### PR TITLE
Fixed errors listed in Issue 35

### PR DESCRIPTION
**Pull request by FlorianTolk**
Made sure that the `inScheme` matched the current version id, but was unique to the overall `id`

### CODE REVIEW

**Comment by jhaag75** [comment]
Thanks Floria. However, the ids of the concepts should not be changed.

**Comment by jhaag75** [comment]
only inscheme should be updated. Can you submit another PR?

**Comment by FlorianTolk** [comment]
I changed the id's of some of them since they are supposed to be unique from the version ID. If the IDs have a version number, I just removed them. Do you still want me to undo that change?

**Comment by jhaag75** [comment]
Thanks Florian!

**Pull request merged**
