### PR TITLE
Florian tolk patches

### PR DESCRIPTION
**Pull request by FlorianTolk**
Fixed Issue #87

### CODE REVIEW

**Comment by jhaag75** [comment]
Hi Florian. When will these be committed into master?

**Comment by FlorianTolk** [comment]
Good Morning Jason,

We are still looking at fixing issue #88. Once we have that commited to this branch we will merge all at once.

**Comment by jhaag75** [comment]
Thanks for the info.

**Comment by blakeplock** [comment]
Hey @FlorianTolk -- Can we get these merged? Running validation in DATASIM and they are all hitting issues.

**Pull request merged**
