### PR TITLE
Creation of Audio profile

### PR DESCRIPTION
**Pull request by johngriner91**
Similar to the 'Video' profile, this would be for audio only content. Extensions and interactions that are present in the 'video' profile but don't apply to audio-only content have been removed.

### CODE REVIEW

**Comment by FlorianTolk** [comment]
Good Morning @johngriner91 and @jhaag75 would it be possible for you two to join the xAPI Working Group call on the 15th? This is a weekly GoTo meeting that begins around 2:30pm Eastern time to discuss changes to the xAP spec, suggested profiles, etc.

I believe this would be the ideal place discuss the addition of this profile to our vocab server

To join you can follow this link:
[https://global.gotomeeting.com/join/686232837](https://global.gotomeeting.com/join/686232837)

I hope to see you there!

**Comment by jhaag75** [comment]
Yes, I'll be there. Thanks Florian.

**Comment by johngriner91** [comment]
It's on my calendar. Thank you.

**Comment by jhaag75** [comment]
Some corrections were recently made to the video profile after our last Video CoP meeting:
https://github.com/adlnet/xapi-authored-profiles/tree/master/video/v1.0.3

Not sure if you want to update the audio profile to match these templates, but wanted to let you know.

**Comment by Digitdev** [comment]
Just a thought here but are we going to have profiles for each media format out there?  There is a lot of  overlap between this and the video profile as comments above.  With verbs like paused do we really need one for every profile for example.  Can't we just modify  paused description to something like "paused the media or activity"

I think we add a lot of confusion for analytics and developers of content having verbs that essentially mean the same thing.  Context activities etc... can be used to differentiate the media.

There was talk of another profile the other day for virtual reality that I think should just be in the serious games profile and I believe we could find 85% of what is needed already exists.

Stuart
GBLxAPI profile

**Comment by DataBeeGood** [comment]
In response to Digitdev/Stuart  - On the surface, adding 'audio only' may have seemed useful, but based on the way we use media files, I would suggest Stuart's point is important.  

If we encounter any type of READ-ONLY **media file** in the wild, we simply determine the **codec** and apply an appropriate **media player** program.  So perhaps we should adjust our thinking and apply a **"Media File Player" Profile** to handle **"Media File Player" Activity Statements.**   

I believe it could handle any "recording" being "played back" using any identified "player."  So audio might not use some of the verbs for videos, and next year when everything is XR objects in scenarios -- a few verbs might be added  :)  ... all in one continuously additive reference as … Media File Player profile.  It might work well for legacy media systems as well... like laser discs, CD, DVD, movie reels or vinyl record discs, etc...

Regarding the stretching to XR... I worked on an XR performance tracking system project recently and found that Demo Mode was not much more than a fancy kind of recording being played for the learner.   This "Media Player" happened to use AR/XR controls and allowed a 3D freedom for viewing... so perhaps an additional verb or extension etc... 

To the mention of XR and serious games... Once in Performance Tracking Mode, this XR system required something more like the idea of ARLEM - too complex to be a "serious game" -- too virtual and restricted in scope to be a "simulator,"  and very AR heavy in structure...  Needed Mixed Reality interface lingo without the additional structure of the game or the simulator.  but that is a little off topic as INTERACTIVE and not a MEDIA PLAYER situation....

Regards.

**Comment by FlorianTolk** [comment]
While I am very pro media profile, I do need to ask how we would handle the current video profile, as it does have a community of practice.
Having both a media profile and an active video profile will also cause confusion.

**Comment by DataBeeGood** [comment]
Thanks FlorianTolk.  
Change is never easy, but it happens!  
I am not at all familiar with the etiquette of proposing this sort of change.  Are you?

**Comment by FlorianTolk** [comment]
@DataBeeGood I am not familiar with the best way to handle these types of changes, but this is an excellent chance to set a precedent!

Every week there is a GoTo Meeting [https://global.gotomeeting.com/join/686232837](https://global.gotomeeting.com/join/686232837) that acts as an open forum for the xAPI community of practice.

This profile was discussed at our last meeting, and while I believe we are moving towards an agreement on how to handle situations like this, but I believe everyone would benefit from continuing this conversation at least for another week before making this merge.

This is a weekly GoTo meeting that begins around 2:30pm Eastern time and I'm sure everyone would be thrilled to have more people weigh in on this issue.

Hopefully @jhaag75 and and @johngriner91 won't mind another call before moving forward on this.

**Comment by DataBeeGood** [comment]
Thanks FlorianTolk,

Happy to share insights from my information systems perspective.
I have been following IEEE groups, but have heard about other groups.  
I also attended iFEST last year so I could get a grounding in the state of the art.

What day of the week? is the regular call?

**Comment by FlorianTolk** [comment]
@DataBeeGood This is a regular call every Wednesday. I really look forward to seeing you there! hopefully you'll be able to help everyone find a compromise on a topic like this.

Obviously if you know anyone else who may want to weigh in on this conversation, please don't hesitate to invite them as well.

I look forward to hearing from you!

If there are any questions or concerns, please don't hesitate to reach out to me, I'll do my best assist!

**Comment by DataBeeGood** [comment]
Thanks again.  I am noting that the Video Community of Practice has terminated their calls after 3 years of work -- as of May 9, 2019 - it figures... :) I will take a serious look at the work I did last year and see if I can use any of it regarding profiles.
https://github.com/liveaspankaj/xapi-video-cop/wiki/43.-xAPI-Video-CoP-Meeting-Minutes-–-May-9th%2C-2019

**Comment by FlorianTolk** [comment]
As Yesterday was the 4th Wednesday of the week, our attendance was just 2 people, The discussion planned for the 22nd has been postponed to the 5th to ensure as many people get a chance to voice their concerns as possible.

If there are any questions, please don't hesitate to reach out me!

**Comment by jhaag75** [comment]
You might want to send out a meeting invite if this is a recurring event. I
thought last week was a one-time thing so I didn't have anything on my
calendar this week. If this is a weekly meeting let me know and I'll update
my calendar. But this still doesn't inform everyone else you want to be
there. Thanks Florian!

**Comment by DataBeeGood** [comment]
@FlorianTolk   I am sorry. Dealing with family illness.  I intend to be there.  Confirming... 5th at 230pm Eastern Time?

**Comment by FlorianTolk** [comment]
@DataBeeGood That's right, I will try to send out an invite to everyone in this conversation today

**Comment by Digitdev** [comment]
@DataBeeGood Hello All - I just got back from overseas.  It looks like there is a plan to have a call on June 5th - Is that correct?  I can probably jump on to that based on my current calendar.

**Comment by FlorianTolk** [comment]
@Digitdev, yes there is a meeting today at 230 Pacific Time

**Comment by DataBeeGood** [comment]
@FlorianTolk isn't that 2:30 Eastern Time?

**Comment by FlorianTolk** [comment]
@DataBeeGood and @Digitdev My apologies, it is Eastern time.
We had to cut today's meeting short, but will do it again in a week (6-12-19) same time and url as last time

**Comment by jhaag75** [comment]
I will try to join as well. Can you please send out a calendar invite?

**Comment by jhaag75** [comment]
Called in today for the 6/12 meeting but nobody was there. Let us know if I
can support future meetings or if this meeting info has changed.

**Comment by gblxapi** [comment]
Sorry I totally missed this.  Is there a link to the call in info somewhere? If I don’t get it on my calendar it is gone ☺ Will do my best for the next one when announced.

**Comment by FlorianTolk** [comment]
@jhaag75  and @gblxapi the meeting just started and can be found at [https://global.gotomeeting.com/join/686232837 ](https://global.gotomeeting.com/join/686232837) 

The meeting begins at 2:30 Eastern Time.

**Comment by johngriner91** [comment]
So, after some offline discussion, I wanted to give an update here. Current this PR stands up an audio profile that declares a new audio activity type and utilizes the video profile verbs.

In our discussion last week, we discussed just updating the video profile descriptions to be more flexible of the content type. However, in looking down that path, a couple statement properties clearly indicate the content is a 'video' type:

1. The activity id explicitly notes a 'video' type. https://github.com/adlnet/xapi-authored-profiles/blob/master/video/v1.0.3/video.jsonld#L64.

2. The statement's `objectActivityType`: https://github.com/adlnet/xapi-authored-profiles/blob/master/video/v1.0.3/video.jsonld#L395

Not sure what the best path forward here is. One option is changing what is required in the statements. If having the id/objectActivityType be optional or have a flexible value is alright, then I can update the video profile to reflect that . Otherwise, we may end up needing to continue with this PR as is.

**Comment by FlorianTolk** [comment]
This is dependent of if you want to track the difference between video and audio (I would suggest allowing this) Then you can create an audio activity type, in addition to the video activity type.

Any instance where either value would work within the templates of this profile, I would suggest setting the profile to allow for both values.

Otherwise we'd have to replace the video activity type with a "media" activity type, which means we track slightly less potentially important information.

**Pull request merged**
